openapi: "3.0.0"
info:
  version: 0.0.1
  title: Spring Pet WebApp
paths:
  /kafkaEvent:
    get:
      summary: Retrieve all kafka events
      operationId: getEvents
      tags:
        - KafkaController
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KafkaEvents"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create new kafka event
      operationId: createEvent
      tags:
        - KafkaController
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KafkaEvent'
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    KafkaEvent:
      type: object
      properties:
        id:
          type: integer
          format: int64
        info:
          type: string
    KafkaEvents:
      type: array
      items:
        $ref: "#/components/schemas/KafkaEvent"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
security:
  - BasicAuth: []